version: '3'
services:
  redis-cluster:
    image: grokzen/redis-cluster:4.0.12
    environment:
      IP: 0.0.0.0
      SENTINEL: 'false'
      STANDALONE: 'true'
    hostname: redisdocker
    ports:
      - '7000-7007:7000-7007'