version: '3.3'
services:
  mysql:
    build: ./docker/mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: horiga
      MYSQL_PASSWORD: horiga
    ports:
      - 3306:3306
    hostname: mysqldocker
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf/:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    tty: true
    stdin_open: true
    privileged: true
