version: '3'
services:
  mysql:
    build: ./docker/mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: horiga
      MYSQL_PASSWORD: horiga
    ports:
      - 3306:3306
    hostname: mysqldocker
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf/:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    tty: true
    stdin_open: true
    privileged: true

  redis-cluster:
    image: grokzen/redis-cluster:4.0.12
    environment:
      IP: 0.0.0.0
      SENTINEL: 'false'
      STANDALONE: 'true'
    hostname: redisdocker
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
      - 7006:7006
      - 7007:7007
    tty: true
    stdin_open: true
    privileged: true
