version: '3'
services:
  redis-cluster:
    image: grokzen/redis-cluster:4.0.12
    environment:
      IP: 0.0.0.0
      SENTINEL: 'false'
      STANDALONE: 'true'
    hostname: redisdocker
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
      - 7006:7006
      - 7007:7007
    tty: true
    stdin_open: true
    privileged: true